package com.eMart.main.service;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.io.ClassPathResource;
import org.springframework.core.io.FileSystemResource;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;
import org.springframework.web.multipart.MultipartFile;

import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.internet.AddressException;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.mail.util.ByteArrayDataSource;
import java.io.*;

@Service
public class EmailService {

    @Autowired
    private JavaMailSender javaMailSender;

    public void sendMail(ByteArrayOutputStream file)  {
      /*  SimpleMailMessage msg = new SimpleMailMessage();
        msg.setTo("mot@gmail.com");
        msg.setSubject("Testing from Spring Boot By monish");
        msg.setText("Hello World \n Spring Boot Email");
        javaMailSender.send(msg);*/

        try{
            MimeMessage message = javaMailSender.createMimeMessage();
            // Enable the multipart flag!
            MimeMessageHelper helper = new MimeMessageHelper(message,true);
            helper.setFrom("emart@gmail.com","system11");
            helper.setTo("monishwaranenkat@gmail.com");
            helper.setSubject("e-mart report");

            ByteArrayOutputStream outputStream = null;

            outputStream = file;
            byte[] bytes = outputStream.toByteArray();
            DataSource dataSource = new ByteArrayDataSource(bytes, "application/pdf");
            helper.addAttachment("test.pdf",dataSource);

            helper.setText("<h1>generated by system</h1>",true);
            javaMailSender.send(message);
        }catch (UnsupportedEncodingException e) {
            e.printStackTrace();

        } catch (MessagingException e) {
            e.printStackTrace();
        }
    }
}
